import type { Metadata } from "next";
import {  Kanit, Archivo_Black,Prompt } from "next/font/google";
import "./globals.css";

const archivo = Archivo_Black({
  variable : "--font-archivo",
  subsets: ["latin"],
  weight: ['400']
})

const kanit = Kanit({
  variable: "--font-kanit",
  subsets : ["thai"],
  weight: ["200","400","300","500","600","700"]
});

const prompt = Prompt({
  variable: "--font-prompt",
  subsets : ["thai"],
  weight: ["100","200","400","300","500","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable}${archivo.variable} ${prompt.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
